### ISSUE TITLE
Patent Section confusing

### ISSUE THREAD

**Issue by jakeswenson** [kemitchell/api-copyleft-license#32]
Just discovered this license, and i love the idea. I do find the patent section's wording confusing.

> The developer licenses you to do everything with this software that would otherwise infringe any patent claims they can license.

I suppose i am the most confused with `that would otherwise infringe any patent claims they can license.`

You're allowed to do everything that would normally constitute infringement in the event the owner/developer were to patent something?

I think i might be starting to grok this sentence, but it's hard to be sure.  

Thanks again and such a cool idea!

**Comment by kemitchell** [comment]
You're on the right track.

Most lawyer-drafted patent licenses spell out all the things that you can get sued for doing under a patent.  For example, here's from [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0#patent):

> 3. **Grant of Patent License**. Subject to the terms and conditions of this License, each Contributor hereby grants to You a ... patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, ...

Where does that list of verbs come from? The Patent Act. To be more specific, [title 35, section 271(a) of the United States Code](https://www.law.cornell.edu/uscode/text/35/271):

> Except as otherwise provided in this title, whoever without authority makes, uses, offers to sell, or sells any patented invention, within the United States or imports into the United States any patented invention during the term of the patent therefor, infringes the patent.

Rather than list out all the means of patent infringement, Parity just references the list as a whole. That  gives a number of advantages.

First, it's easier to understand. You don't need to know all the ways you can infringe a patent under the law.

Second, there's no risk of the lists in the law and the lists in Parity going out of sync. You don't have to "diff" Parity's patent grant against the Patent Act. If the Patent Act changes, or courts add new judge-made rules creating more ways to infringe a patent, Parity covers them automatically.

Finally, it's more portable across jurisdictions. Countries differ in what counts as patent infringement, and in the words they use for those actions. Apache 2.0 is a well written license. But we could criticize it for using the terms of US law, without specifying that US law should govern how we read or apply its terms.
