### ISSUE TITLE
What does it mean to "expose functionality"?

### ISSUE THREAD

**Issue by laughinghan** [kemitchell/api-copyleft-license#35]
First of all, I love what you're doing, and I similarly disappointed that the OSI was unable to work with Mongo to get the SSPL accepted.

I'm worried about this passage (not coincidentally, your primary innovation):

> exposing this software's interfaces and functionality to other software

What exactly does "exposing" mean? If my database, Ognom, is licensed under the API Copyleft License, and its API can be used to create, read, update, and delete records of data, and you build a personal notes app on top of Ognom that lets people create, read, update, and delete notes, the idea is that your app is only subject to the permissive terms, right? Will it be clear to the courts and developers why that's not "exposing [Ognom's] functionality"?

What if your app exposes an API for other apps to use to create/read/update/delete notes, wherein they can store arbitrary records of data? Then do the copyleft terms kick in? (That's not even hypothetical&mdash;people can and do use Google Sheets as their backing "database"; presumably, Google Sheets itself is backed by a traditional database.)

It can't be that my app has limitations that Ognom doesn't--presumably, if I built a thin wrapper around Ognom that just limited one piece of functionality (it's just Ognom but you can't store ints, only floats), that should still be subject to the copyleft terms.

I have similar concerns with the GPL, AGPL, and SSPL, all of who define "covered works" as just "a work based on the Program" (so...is AWS "based on" Redis?). Separately, SSPL also defines a special copylefted category "Service Source Code", which includes "all programs that you use to make the Program or modified version available as a service, [...] all such that a user could run an instance of the service using the Service Source Code you make available." Does that include the OS? Process monitoring tools?

Maybe I'm overthinking this&mdash; if it's obvious to me whether something should be covered by copyleft or permissive terms, it'll be obvious to the courts. Still, I'm worried it's not more obvious.

**Comment by laughinghan** [comment]
I'm wonder if we could invoke the concept of software "portability" or "compatibility"—if my app uses Redis hosted by Aiven, AWS is intentionally designed so that it's "easy" to port my app to use Redis on AWS. PostgreSQL and MySQL don't fully conform to the SQL standard, and extend the standard in many ways, but are _mostly_ compatible, at least partly with the intention that an app backed by one SQL database could be ported to the other with a limited (if nontrivial) amount of effort.

"[Amazon DocumentDB (with MongoDB compatibility)](https://aws.amazon.com/documentdb/)" is expressly designed so that any Mongo-backed app can be easily ported over to it. As far as we know, DocumentDB was clean-room reverse-engineered, without using any MongoDB source code; but in a hypothetical world where DocumentDB was a wrapper around MongoDB, and MongoDB used a hypothetical revision of the API Copyleft License that mentions "compatibility", perhaps we could point to that as the reason why DocumentDB must be open-sourced.

By contrast, the hypothetical personal notes app API would be completely unlike a database API like Ognom's, and not designed for compatibility or for other apps to just port their app from Ognom to the notes app.

One wrinkle: while the API Copyleft License would/should require the hypothetically infringing DocumentDB to be open-sourced, I don't think it would require the rest of AWS to be open-sourced the way the SSPL is apparently intended to, since I'm pretty sure AWS invokes the databases it hosts using their public interfaces?

**Comment by kemitchell** [comment]
> I'm worried about this passage (not coincidentally, your primary innovation)

Love it! Will finish reading now.

**Comment by kemitchell** [comment]
Sorry for lots of pull-quoting. You’ve given me a lot!

> Maybe I'm overthinking this

Nay, sir!

> if it's obvious to me whether something should be covered by copyleft or permissive terms, it'll be obvious to the courts.

I wish that were so.

But we can’t reliably guess how, exactly, time-and-resource-deprived judges will misunderstand technical concepts. So we write it as clearly as possible for our own kind, and apply “Are courts particularly likely to misunderstand this?” as a finishing step.

> Still, I'm worried it's not more obvious.

I don’t think we can make it obvious without also making the license specific to particular technology, which will go out of date in short order. So we accept that we’ll fail to meet “obvious” to any absolute standard for the level of generosity we need, but also that if we don’t try, we’ll fail harder.

This is *absolutely normal* in legal drafting. We’re using natural language to pattern match on reality, not a formal language to pattern match on discreet inputs. There are only trade-offs.

**Comment by kemitchell** [comment]
> One wrinkle: while the API Copyleft License would/should require the hypothetically infringing DocumentDB to be open-sourced, I don't think it would require the rest of AWS to be open-sourced the way the SSPL is apparently intended to, since I'm pretty sure AWS invokes the databases it hosts using their public interfaces?

It was my intent to draft this license to reach less code than SSPL, as you describe. I’m very grateful for your confirming read!

**Comment by kemitchell** [comment]
@laughinghan this is a magnificent issue! The incision points of your analysis—“interfaces”, “expose”, and “functionality”—coincide *exactly* with my areas of lingering focus. It’s as if you read the license and at once read my mind.

You’ve put evident time, thought, and care into the main thrust of your feedback. Forgive a delay as I gather strength to return in equal measure, as your prompt deserves. I need to review old notes, collect thoughts, get this back in scarce short-term memory, and give good thought to the structure that gives us best chance of finding a PR together.

In the meantime, if you have time, please send a PR adding yourself to `THANKS.md`. I’ll merge immediately. Well earned the moment you opened this.

**Comment by kemitchell** [comment]
@laughinghan I haven't forgotten about this issue. I've been dealing with some health stuff. Hope to get back to you soon.

**Comment by laughinghan** [comment]
Oh no, I wish you the very best for your health!

**Comment by kemitchell** [comment]
@laughinghan you correctly point out all the hardest line-drawing problems.

API Copyleft starts with a general rule:

> ...With two exceptions ... you must contribute all changes and additions to this software, as well as all software that invokes this software's functionality...

The exception that concerns us is "applications":

> You need not contribute software that only invokes this software's functionality through the interfaces this software exposes, without exposing this software's interfaces and functionality to other software.

If the rule were that applications can't expose _all_ of the software's interfaces or functionality, it would be easy to avoid copyleft, by omitting some interface item or specific feature. If the software is a database, perhaps I'd omit its replication APIs, or its Cyrillic alphabet transcoding functionality.

On the other hand, if the rule were that applications can't expose _any_ of the software's interfaces or functionality, it would be essentially impossible to identify any application that definitely isn't reached by copyleft. If the software is a database, and the application is an address book manager, isn't the address book manager providing the data-storage functionality of the database?

So then the question becomes: How much of the interface, or how much of the functionality, does a program have to expose to other programs to become a "wrapper" reached by copyleft, rather than an "application" that's not?

I think you're headed in the right direction with "portability" and "compatibility". In technical or economic terms, I think the crux is whether the new program is a _substitute_ for the licensed software. In business terms, I think the crux is whether the new program would represent closed competition for the licensed software.

If we can express that compatibility-substitution-competition idea well enough, perhaps all the language about interfaces and functionality simply becomes unnecessary, or helpful only to clarify the more general rule.

Let me see about a pull request tweaking the language of Applications.

**Comment by kemitchell** [comment]
Thinking a bit more about how to express the idea of a substitute for the software.

One way to do that might be focus on the specialization aspect of an application. If the licensed software is a database, and the application is a contact management app, the contact management app wraps the data-storage functionality of the database, but not in its general form. Rather, the app specialized the data-storage functionality of the database to a particular use case.

**Comment by laughinghan** [comment]
I think bringing up the idea of a "competition" and "substitute" is _brilliant_. A narrow, technical definition of compatibility might make it too easy to avoid copyleft by introducing some trivial intentional incompatibility, like prefixing every method name or something.

The notes app example I brought up above is still tricky though. Customers _could_ perhaps decide (only at the outset of a project, probably) that they don't need a "real" database like Ognom, and end up just using the notes app API, which kind of makes them competing, though it'd still be difficult to call them substitutes.

Maybe the narrow, technical definition of compatibility isn't so bad. In the hypothetical world where proprietary DocumentDB was a wrapper around an API-Copyleft-licensed MongoDB, and therefore DocumentDB had to be incompatible, it would be no small burden on them that the ecosystem of MongoDB tools like Mongoose and tutorials, blogposts etc would have to be ported or patched to support both. They appear to specifically have not wanted that: "...allowing you to use your existing MongoDB drivers and tools with Amazon DocumentDB..." [(DocumentDB homepage)](https://aws.amazon.com/documentdb/).

**Comment by kemitchell** [comment]
In my mind it's boiling down to:

If you can collaborate, rather than compete, then collaborate. Otherwise, you're free to do what you like.

I'm hesitant to try to express that indirectly, through concepts like compatibility or modification of files (MPLv2) or the like. All of those ways involve introducing yet another fuzzy boundary, like "compatibility".

**Comment by laughinghan** [comment]
Iiiinteresting, that makes a lot of sense. I think it makes a lot of sense to articulate the exception in terms of "specialization", then.

**Comment by laughinghan** [comment]
Hmmmm actually, doesn't a specialization of a tool still compete with the general-case version of the tool? Most of the time adoptees of a piece of software have _one_ use case for it, which by definition will be narrower than all the uses of the software. If they tweak it to be better for their use case, don't we want them to contribute it back, so that the software is now better for one of its uses? It seems like we want to discourage them from keeping their tweak proprietary and then, say, selling it to others with their use case, who will then _substitute_ the proprietary tweaked version for the open source version.

I think "competing" and "substituting" are a really good articulation; I think specialization might not be.

**Comment by kemitchell** [comment]
@laughinghan I think I agree. First because having two standards is twice as complex. Second because the example you gave is _fundamentally_ a wrapper. Wrappers substitute, and wrappers compete.

We could dream up a project where _every_ fork is to some extent specialized, and nobody uses the generic original directly. Those forks would still have to contribute changes and extensions to the generic core. But they'd all be free to keep their specialization layer closed. Collaboration becomes a matter of technical implementation happenstance: What you need to do is a change or extension, rather than a wrapper.

**Comment by laughinghan** [comment]
> We could dream up a project where every fork is to some extent specialized, ...

To be clear: you're bringing up such a scenario because it's one you'd want to prevent, right?

**Comment by kemitchell** [comment]
Yes. The thrust of the license is that folks should work together on the licensed software. Requiring no contribution because all potentially contribution-worthy work is in some sense specialized defeats that purpose.

**Comment by kemitchell** [comment]
@laughinghan I'm closing this now, because it's been a while. But if you have any further thoughts, especially about #40, please feel free to weigh in at any time!
