### ISSUE TITLE
Mentioning class extension in Interfaces

### ISSUE THREAD

**Issue by simerplaha** [kemitchell/api-copyleft-license#43]
For clarity should **Interfaces** mention class extensions? Similar to how [LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html) has the following

>Defining a subclass of a class defined by the Library is deemed a mode of using an interface provided by the Library.

**Comment by kemitchell** [comment]
The relevant text from #40 at the moment is:

> You don't have to contribute any software that only invokes this software's functionality through the interfaces this software exposes, unless that software exposes so much of this software's interfaces or functionality to users or other software that it becomes a practical substitute for this software.
>
> Interfaces exposed by this software include all the interfaces this software provides users or other software to invoke its functionality, such as command line, graphical, application programming, remote procedure call, and inter-process communication interfaces.

@simerplaha if you sublcass a base class in the licensed software, then run that subclass, would it be safe to say that the new subclass "invokes the licensed software's functionality"?

**Comment by simerplaha** [comment]
I think subclassing a base `class` in the licensed software, then running that subclass would be an extension/improvement in most cases since a library author would generally expose an `interface` or `trait` to allow these extensions instead of exposing a `class`.

Extending or implementing an `interface` or `trait` would be "invoking the licensed software's functionality".

**Comment by kemitchell** [comment]
@simerplaha I take it you mean "class", "interface", and "trait" in the Scala senses of those terms?  I fear their meanings differ in potentially significant ways across languages.  In Rust, for example, "trait" is the main means for organizing data, not "class". There are no "classes".

This is part of the reason I'd like to _avoid_ using any more specific words than "interface" in the API Copyleft license.  If we cover "class" specifically, do we have to note in what sense we mean "class"?  Do we have to cover "traits" and "prototypes" and "mixins" and "templates" and "generics", too?

Another part of the reason is the rules courts use to interpret legal terms when they're not clear in a particular situation.  If we add a specific clarification for "class", they may read the _lack_ of a clarification for other kinds of concepts the wrong way. And the appearance of a more specific rule---for classes---to do the same work as a more general rule---the rule on "interfaces"---may lead them to read the general rule too narrowly.

For all those reasons, I'd prefer to make "interface" and the way it's fleshed out in the license text as all-encompassing as possible.

I do have a change in mind that I think you may like. Give me sec. I'll make a PR.

**Comment by simerplaha** [comment]
Ah yes. That makes sense. This can be closed.

**Comment by simerplaha** [comment]
I thought that since LGPL mentions `class` it would be generic concept in most programming languages indicating a functionality. The languages I'm familiar with are JVM languages, Haskell and JS.

By `interface` and `trait` I meant anything that defines contract between an implementation. Scala doesn't have the term `interface` either.  But the PR looks good 👍

Is including "local procedure call" along with "remote procedure call" required in the Interface section to indicate local linking which would also cover "subclassing" without explicitly using the term `class`?
> functionality, such as ... local and remote procedure call ...

 or is that not necessary because it's covered under "all the interface" in the following text?
> Interfaces exposed by this software include all the interfaces this software ...

**Comment by kemitchell** [comment]
I don't know that I've ever seen the phrase "local procedure call".
